name: mapduo
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_mapbox_navigation: ^0.1.7
  intl: ^0.18.0
  location: ^5.0.3
  # mapbox_gl: ^0.16.0
  mapbox_search: ^3.2.0
  permission_handler: ^10.3.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/config/
    - assets/style.json
